features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/all/themes/custom/snownow/logo.svg
favicon:
  use_default: true
